### ISSUE TITLE
Feature Request: Router Wildcard/Router Inventory Cleaning

### ISSUE THREAD

**Issue by Derpford** [MeatWheeze/NeepMeat#17]
Occasionally, my ejectors stop ejecting, and I think it has to do with my router not having a path for one of the items I'm moving. However, I can't tell *which* item clogged the router unless I happened to watch it go in.

There are two features I want for helping with this:
1. a "wildcard" setting for the router, which directs all items that don't match other filters toward that output;
2. Some way of seeing the router's current inventory, so that I can tell which items are clogging the system.

**Comment by Derpford** [comment]
Note that a "wildcard" route can be sort-of achieved by having a router that is closer to the input than an unfiltered inventory. I don't think this is quite perfect, though; I don't fully understand the pneumatic tube logic.

**Comment by MeatWheeze** [comment]
I'm not sure what's happening here, since routers do not have inventories. Ejectors do have internal inventories. When there is a direct route to a storage or router, they will check whether the route is viable. If it isn't the item will remain stored in the ejector until the route is clear. 

Currently the 'wildcard' approach you describe is what I intended since the pipes will try to insert their items into adjacent storages or routers before they check adjacent pipes.
