### ISSUE TITLE
Compatibility Issue with Infinite Dimensions? [Fabric 1.20.1]

### ISSUE THREAD

**Issue by Dumpling00** [MeatWheeze/NeepMeat#8]
Greetings. HUGE fan of this mod! I found it by chance and I absolutely fell in love with it first sight.

As per title, I've found myself in a bit of a weird pickle - when messing around with another mod called Infinite Dimensions, the game crashes and from the report, it seems like NeepMeat is involved, somehow. Not sure exactly where the compatibility issue comes from - I've already contacted the dev from Immersive Portals and thought I'd mention it here too in hope you could kindly help us shed some light on this.

The crash is 100% replicable and always happens when shift-right-clicking the Portal after throwing a bookandquill in it (as per protocol to activate it and generate a random dimension in Infinite Dimensions mod) At which point, the game crashes.
This is the session log - All I did was open a world and activate the portal to illustrate the issue.
[crash-2024-03-21_02.25.36-server.txt](https://github.com/MeatWheeze/NeepMeat/files/14726498/crash-2024-03-21_02.25.36-server.txt)

Was wondering if anything could be done at all?

Thank you for your time and consideration!

**Comment by unilock** [comment]
This is because Infinite Dimensions doesn't invoke Fabric API's `ServerWorldEvents.LOAD` when loading its dimensions, which needs to be done manually by them since they forgo vanilla's own dimension loading tactics.  
I made a fork of the mod with a fix for that (PR pending): https://github.com/unilock/ProjectInfinity/tree/event

**Comment by MeatWheeze** [comment]
Not sure how soon the PR will be merged, but this is fairly easily bypassed on my end. I should probably have used computeIfAbsent here instead of listening to the event: https://github.com/MeatWheeze/NeepMeat/blob/1d7ed7d13f00b78a0b30fc0eb28ae3e23a55f34a/src/main/java/com/neep/meatlib/api/event/InitialTicks.java#L35

**Comment by MeatWheeze** [comment]
I've released the fixed version. Hope this helps. 

https://modrinth.com/mod/neepmeat/version/0.2.19-beta+1.20.1
